package dev.lemma.finiteworlds.core.hydrology;

/**
 * One high-resolution physical river-centerline sample generated by
 * Hydrology Pass 2G.
 *
 * blockX/blockZ are finite-world block coordinates. plannedBedElevation,
 * widthBlocks, and depthBlocks are still planning metadata only; no terrain
 * is carved by this pass.
 */
public record RiverCenterlinePoint(
        double blockX,
        double blockZ,
        double distanceBlocks,
        double plannedBedElevation,
        double widthBlocks,
        double depthBlocks,
        double lateralOffsetBlocks
) {
}
